functionsDirectory = "C:\\Users\\User\\Desktop\\highplus-marketing\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
redirects = []

[build]
publish = "C:\\Users\\User\\Desktop\\highplus-marketing"
publishOrigin = "config"
functions = "C:\\Users\\User\\Desktop\\highplus-marketing\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/*"

[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "no-cache, must-revalidate"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "no-cache, must-revalidate"